### ISSUE TITLE
Parser Quest

### ISSUE THREAD

**Issue by Adamantios** [Adamantios/PDDL-Solver#1]
What about using this [Parser](https://github.com/thiagopbueno/pddlparser-pp)?

**Comment by eakirtas** [comment]
LGTM, user seems to be active and a [RosPlan](https://github.com/dgerod/task-planning) (?) planner  already has been implemented with it

**Comment by efikalti** [comment]
Created a shared library of pddl-parser and imported it in a new application. I have uploaded the implementation in 8c99fc126eb155a291cbe54380e4c1c3b0b3a5d3.
However I used make to build both pddl-parser and the planner.
